### ISSUE TITLE
[DataCap Application] Commoncrawl

### ISSUE THREAD

**Issue by nike-mp** [filplus-bookkeeping/DAYOU#3]
### Version

1

### DataCap Applicant

FileTech

### Project ID

FileTech-02

### Data Owner Name

CommonCrawl

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://commoncrawl.org/

### Social Media Handle

https://commoncrawl.org/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

4PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1wy6ik2ns5oypb4yx6uhuf55hxbzihugg674jzvi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FileTech focuses on providing excellent data storage solutions. We have a passionate and knowledgeable team with extensive experience and expertise in the field of data storage. Whether it's data storage, data management, data recovery, or data center design and construction, we possess abundant technical capabilities and solutions.

At FileTech, we understand the importance of data in modern businesses. We not only offer high-performance data storage devices and solutions, but also provide comprehensive data management tools to help clients efficiently organize, classify, and protect their data assets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Common Crawl maintains a free, open repository of web crawl data that can be used by anyone.
Primary training corpus in every LLM.82% of raw tokens used to train GPT-3.Free and open corpus since 2007.Cited in over 8000 research papers.3–5 billion new pages added each month.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### Please share a sample of the data

```text
357-resule 
2020-08-25 17:22:47  398.4 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf13.grib2
2020-08-25 17:22:52  396.0 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf14.grib2
2020-08-25 17:22:52  394.6 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf15.grib2
2020-08-25 17:22:52  390.2 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf16.grib2
2020-08-25 17:23:08  387.1 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf17.grib2
2020-08-25 17:23:05  384.8 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf18.grib2
2021-09-28 03:48:22   31.6 KiB index.html

Total Objects: 43282174
   Total Size: 2.1 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03071472- HK
f03028318- HK
f02830476- Guangdong
f03028326 -Guangdong
f03028321- HK
f03028325- HK
f03028310- HK
f03028315- HK
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nike-mp** [comment]
Hello, on behalf of the taskmaster, thank you for your reply. Although this is our first request, we have enough experience. Our technical staff have worked in a well-known Filecoin company for three years, and we have rich experience in data downloading, processing, and saving. We conduct secondary development based on https://github.com/karust/gogetcrawl. After downloading a batch of data from Amazon Web Services S3, it automatically handles packaging and generates car files. As long as the same download parameters are set, the same piececid car file can be downloaded and generated, ensuring that different SPs can download and encapsulate the same file, ensuring that the data backup meets the requirements. After the car file is generated, the corresponding unit data will be generated at the same time, including filename, data_cid, piece_cid, piece_size and other information and written into the csv file. The csv file is the datacap distribution file that will be used later, and the file name is the tag name and starting position of the downloaded data set. Based on the metadata file, you can tell which portion of the total data set is saved by each LDN. Data download can be performed directly on the SP's device, or it can be processed and mailed to the SP through the hard disk.
We are currently ready, with staking, data downloads, personnel, etc. all ready. Hope to get your help.

50T seems relatively small. Can you give us 300-600TiB? Because we have cooperated with 8-10 SPs, it is difficult to allocate 50T in the first round. We may need 512TiB for better allocation.

**Comment by nike-mp** [comment]
checker:manualTrigger

**Comment by nike-mp** [comment]
Data is not updated

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by nike-mp** [comment]
checker:manualTrigger

**Comment by nike-mp** [comment]
checker:manualTrigger

**Comment by nike-mp** [comment]
The data has not been updated for 10 days. We close this application and reapply. Thank you. @DaYouGroup

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger
